name: Teste de docker 

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image (e.g., commit ID or version)'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push with DockerfileMultiStaging
        uses: docker/build-push-action@v6
        with:
          context: ./helloSpring
          file: ./helloSpring/DockerfileMultiStaging
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-java-multistaging:${{ github.event.inputs.image_tag }}

      - name: Build and push with DockerfileOneStag
        uses: docker/build-push-action@v6
        with:
          context: ./helloSpring
          file: ./helloSpring/DockerfileOneStag
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-java-onestag:${{ github.event.inputs.image_tag }}